### ISSUE TITLE
Minor tweak to instructions

### ISSUE THREAD

**Issue by ruben-cit** [svolodarskyi/docker_turtorial#1]
Hey!

This ticket is an excuse to say thank you more than anything else. Found this guide to be a real easy way to bootstrap myself to a postgres <-> jupyter setup. So thank you!

One minor note: I ran into some friction with the following part:

```
FROM jupyter/scipy-notebook:33add21fab64

RUN pip3 install pandas psycopg2     
```

You actually install the `psycopg2-binary` because it comes with the dependancies that vanilla `psycopg2` requires.

Anyways, hope you're well. And good job on this guide :)

**Comment by svolodarskyi** [comment]
Hey,

Thank you for the comment and advise, i will incorporate it.

This is the first issue in my repo. Thank you for that! 

Thank you for the feedback. Hope you are well, as well!
